### ISSUE TITLE
Frontend for Private Preview

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#1]
```[tasklist]
### General
- [ ] https://github.com/grafana/loki-explore/issues/20
- [ ] https://github.com/grafana/loki-explore/issues/6
- [ ] https://github.com/grafana/loki-explore/issues/7
- [ ] https://github.com/grafana/loki-explore/issues/8
- [ ] https://github.com/grafana/loki-explore/issues/21
- [ ] https://github.com/grafana/loki-explore/issues/22
```

```[tasklist]
### Service index (landing page)
- [ ] https://github.com/grafana/loki-explore/issues/11
- [ ] https://github.com/grafana/loki-explore/issues/23
- [ ] https://github.com/grafana/loki-explore/issues/24
- [ ] https://github.com/grafana/loki-explore/issues/25
- [ ] https://github.com/grafana/loki-explore/issues/26
- [ ] https://github.com/grafana/loki-explore/issues/27
- [ ] https://github.com/grafana/loki-explore/issues/9
- [ ] https://github.com/grafana/loki-explore/issues/28
- [ ] https://github.com/grafana/loki-explore/issues/29
```

```[tasklist]
### Service detail view (main explore interface)
- [ ] https://github.com/grafana/loki-explore/issues/12
- [ ] https://github.com/grafana/loki-explore/issues/13
- [ ] https://github.com/grafana/loki-explore/issues/14
- [ ] https://github.com/grafana/loki-explore/issues/16
- [ ] https://github.com/grafana/loki-explore/issues/17
- [ ] https://github.com/grafana/loki-explore/issues/18
- [ ] https://github.com/grafana/loki-explore/issues/5
- [ ] https://github.com/grafana/loki-explore/issues/30
- [ ] https://github.com/grafana/loki-explore/issues/31
- [ ] https://github.com/grafana/loki-explore/issues/32
- [ ] https://github.com/grafana/loki-explore/issues/33
- [ ] https://github.com/grafana/loki-explore/issues/34
- [ ] https://github.com/grafana/loki-explore/issues/35
- [ ] https://github.com/grafana/loki-explore/issues/36
- [ ] https://github.com/grafana/loki-explore/issues/37
- [ ] https://github.com/grafana/loki-explore/issues/19
```

**Comment by ivanahuckova** [comment]
@matryer we are doing an issue clean up and I am going to close this issue as we have completed the tasks for preview and left over tasks in here are part of GA project. Hope it is okay!
