### ISSUE TITLE
Waterline for a cloud readiness app

### ISSUE THREAD

**Issue by svennergr** [grafana/explore-logs#239]
Those tasks are the waterline of getting the app into a cloud readiness state in "beta". This list might be added or adapted while we work on it.
This does not change the "beta" release stage of the app.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/explore-logs/issues/248
- [ ] https://github.com/grafana/explore-logs/issues/247
- [ ] https://github.com/grafana/explore-logs/issues/246
- [x] https://github.com/grafana/explore-logs/issues/243
- [x] https://github.com/grafana/explore-logs/issues/244
- [ ] https://github.com/grafana/explore-logs/issues/249
- [ ] https://github.com/grafana/explore-logs/issues/250
- [ ] https://github.com/grafana/explore-logs/issues/251
- [ ] https://github.com/grafana/explore-logs/issues/253
- [ ] https://github.com/grafana/explore-logs/issues/254
- [ ] https://github.com/grafana/explore-logs/issues/256
- [ ] https://github.com/grafana/explore-logs/issues/299
```

**Comment by ivanahuckova** [comment]
Done 🎉
