### ISSUE TITLE
[EPIC] Quick search within each area

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#400]
- [x] https://github.com/grafana/explore-logs/issues/368 @gtk-grafana 
- [x] Add search box in Labels @matyax See https://github.com/grafana/explore-logs/issues/400
- [x] #452
- [x] Add search box in Detected Fields (for the fields) @matyax See https://github.com/grafana/explore-logs/pull/418
- [x] [Add search box in Detected Fields (for a selected field's values)](https://github.com/grafana/explore-logs/issues/433) e.g. [find a specific path on this page](https://ops.grafana-ops.net/a/grafana-lokiexplore-app/explore?var-ds=c-R8UWvVk&var-patterns=&var-lineFilter=&var-logsFormat=%20%7C%20logfmt&var-filters=service_name%7C%3D%7Cpyroscope%2Fingester&mode=service_details&actionView=fields&var-labelBy=$__all&var-fieldBy=path&var-fields=&patterns=%5B%5D). @matyax

Thoughts:
* The search box would ideally be in the same place within each tab so people get used to its position
* worth overriding `ctrl+f` to just put focus in that place?

See also:
- [x] https://github.com/grafana/explore-logs/issues/397

**Comment by matryer** [comment]
@cyriltovena I guess this will depend on what's possible/sensible for the backend too?

**Comment by matyax** [comment]
@matryer Can we consider the 2nd and 3rd points done by https://github.com/grafana/explore-logs/pull/418 ?

https://github.com/grafana/explore-logs/assets/1069378/5406343f-4f85-431c-8922-621324b83a26
